[project]
name = "Hy2DL"
version = "2.0.0"
description = " Python library to create hydrological models for rainfall-runoff prediction using deep learning methods"
readme = "README.md"
authors = [
    {name = "Eduardo AcuÃ±a Espinoza", email = "eduardo.espinoza@kit.edu"},
    {name = "Ralf Loritz", email = "ralf.loritz@kit.edu"},
    {name = "Manuel Ãlvarez Chaves", email = "manuel.alvarez-chaves@simtech.uni-stuttgart.de"}
]
license = {text = "MIT"}
requires-python = ">=3.9"

dependencies = [
    "jupyterlab>=4.0.11",
    "matplotlib>=3.8.3",
    "numba>=0.58.1",
    "numpy>=1.26.3",
    "pandas>2.2.0",
    "torch>=2.2.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
